language: java
jdk:
  - openjdk11
install: true
addons:
  sonarcloud:
    organization: xm-online
    token:
      secure: Z4/CxBaYkCvllkSmQ4h2d02HGbv9x6tB9+pYyhlB5XfI2aVvT8hzFlicYkmCjAGkrG+GXu0DE9rGTaTspWiSkQLw+DUGIa8EXalrxPFtX5ER6OoS+/WO8jfFhIlnl0hX1ySWf/kKPkvz6O1bPkwkI88kmp3FG1N0tZmnNl5fWDGySEE+xpzicc4jBnLKCRE2BXuS1xCRJiBr6OHvJGQix7IS5jzubRPs5uYUVhp6uG8stZ6BOMrbSqGghjKEWTSzWhwPxXURQFKMnFx5fbd3da8n8v1xwHOWE+rvvtJckGm8fZu3hCU1r8E1yUlJaAVx9Q8GwFX2DGWp2UY5eyh51XPvLMDCkML6yBd1C4HT2hnwP7DD9OUGcDLge5zHCN9R9IXiHGTWph4nqsY/u/XPH214c3CAmLWHm4oeO1bde6gmLkhrE1jaPdNc+FSfhznFnkqKBCOvoYyQT//r+vs9pFWs4MExBXDJjejhRH+lVa0izqTzGUyjiLzCbwDmpKsze7F4h8/8QfKKU2WImIlwKo+o4+fleB/NnzsVbdfaoudlJZpj9OctXeveggOIS5Dhydjs5vbm3AY80/WUuTrSiQy34fCQFgwt2/GQiyi1ppooYVWdN04M3RQdZA/20PfXV3ypG1bd4aw6Jl5Qc0hrIkibSQjr+RiEAYjadACSElk=
    branches:
      - master

script:
  - set -e
  - "./gradlew --no-daemon --refresh-dependencies clean check test"
  - "./gradlew -x test -Pprod --no-daemon bootWar"
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export DOCKER_REPO=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/^xm-online\//xmonline\//g')
  - export IMAGE_BRANCH=$(echo -n $TRAVIS_BRANCH | sed -e 's/\//-/g')
  - export PROJECT_VERSION="$IMAGE_BRANCH"
  - if [ "$IMAGE_BRANCH" == "master" ]; 
    then 
        PROJECT_VERSION=$(./gradlew -q  getProjectVersion);
        export SONAR_PK=$(echo  -n $TRAVIS_REPO_SLUG | sed -e 's/\//:/g');
        ./gradlew -x test --no-daemon sonarqube -Dsonar.projectKey="$SONAR_PK"
        -Dsonar.projectName="$SONAR_PK" -Dsonar.java.binaries="." -Dsonar.projectVersion="$IMAGE_BRANCH";
        TAGS="$PROJECT_VERSION $PROJECT_VERSION-$TRAVIS_BUILD_NUMBER $(echo $PROJECT_VERSION | awk -F '.' '{printf $1"."$2" "$1}') latest";
    else
        TAGS="$IMAGE_BRANCH $IMAGE_BRANCH-$TRAVIS_BUILD_NUMBER";
    fi
  - docker build -t app-docker-img --label commit_id="$TRAVIS_COMMIT" --label version="$PROJECT_VERSION" --label build_number="$TRAVIS_BUILD_NUMBER" --label build_url="$TRAVIS_BUILD_WEB_URL" --label git_url="$TRAVIS_REPO_SLUG" --label commit_message="$TRAVIS_COMMIT_MESSAGE" -f src/main/docker/Dockerfile .
  - for TAG in $TAGS;
    do
        docker tag app-docker-img $DOCKER_REPO:$TAG;
        docker push $DOCKER_REPO:$TAG;
    done

cache:
  directories:
    - "~/.gradle"
    - "~/.m2"
env:
  global:
    - secure: dQN/4Sv+Kay/S6YSdWCFTZB9KDXtehyqvIbX6Pn8jXkcnBmWH7sPqyjBB0B0c8GyyM3Eh5ckSsgquxBbN79TvrZWGhTTSjF71m/zLJ6sS4t5wMcJL/kC78NoTUiaSkrf6wF6IESNmWYtZRNnLkYrI2t4EASLXJAslqkspg6eZoc1+IC6LiFAcRQIzZVX3rXZf4t/6a+NvoyltBGXejdOB4rMK7qVUVucLm6hY9sLzB558Q2gm/hk9+nSWHKHHm0nhF28EW7KmjuPtFT+2lDf1LlbPRMFnlmUcajg2o0Hna8Stxk195uITPsGfCSBuU1H47mdnpssRrMCBUqvwm5VIPDP+wP31bKNC3r0TDb4MQ3BomCDz28KpcICI8CiRbXEfJudQggTN23BmJfJsqmhNMlZfblnwwSaMpLEmKrlBPRzl4Sq/q6GX8PLUw6gZrdYHaPGRYjAVtVqvswoGJpKwPHwrac+IXvacZ+O4HVovIWeyflInAnfT4vYiu/cBnlFisvMsfaKuyZoOyvrhHfOMZc3MZvwaK+QhCXIlR+THhBORRlj62cmc7V0Blb/uKS9PWEmASNTCpvs2Z0GIhO73wwHKExByS78ijKZLC5Jgxf/dRU08W/K/FlvMbXppAbngR7ZUl7Vw8ER55JKAtyq0QWkIe6Ti5Jxz7k9DIZgcIw=
    - secure: akJm31OzZi9pK9dPajWEni4gR6+hE1ZLrTbFi3Qmq41X5L0JtseZS7H1lClWcAuvxTHUQ14+4Nmyvggyr5Z69FHLkxucd8FopFgH/H0V0qLwTyej4YgvlzmunqQ5anycPZwwesDdwhQ812u528rwCUgaJ4fAyNmQnmP05q18/1RVM8DtQQhY/IPTf8eBdCnmRnZSjTAFUmv2DrHl9NPn0eWYQq7sijeZmQHmk6Od5861GlVxAKg1Pd2VGD9aYx/kW0Cpt5Lvpl+a/tllepWIy72DeRnGgiIABzasYyijwj/sDSjGjHEd/0PfTu/rZi2F5b8LfnH6E/hxtkgUCzr/wJhoK1OkeZH0OpE8kde/qPEKewGZ49R+TP/Qip45CR6I+vX91kmNOPirMuRb8miXZ41DBWoX3PbjojmaA1KpbD4dFwvOBTksBV3mbRQZ41b0kbz4Osp+MIXDE8YGspwPw8lIG4vJxH/VLtUUEIyngoh1wwXyaBoFaWArpxAz1GeFJIh6L5lh4BicVVSSZchbF0XmdOOS6tmARQEcuGYHrGFjwjCiIlN/TZuVJe+HzB6AL+/54nqy4m7lyXo0ugmqXMiZLFFQnO1rsSKIabF48OPrPGiTWhRiQdvTokFCEdyETCUmWFZcG0gGdEExUsvqsMCm7IyOA7YU/dDgZoUbOG4=
    
notifications:
  slack:
    rooms:
      secure: eHvxMZJsCw0vBFWkSsL8YIwam4b43HppJ2m9I+QhW6v/oG7LdxxKeDjpTOn7ramXZxxGZEqibA5QjilMqnraPzHy3lqo7x8+LQXMN5sfDI/B6TZmWZ5r2oEr384L3p02xLwalA2I18xjPwWEQFdERL4wzJNvvXIki/T3X3GGi4pglAfyM6gLTsP0H0fA4WSj8e6Z9Ap7B1UD3tcwKk6+9vbJUEmc+HTx6my317hkmbi/I6mXZb9p63q2yvKnjEaU8vlULYls3gPxQDrozLbDMN5dFATS2p5mqrJVNY8r3gcJb0l38eFVzl09YWiNTfEWgT9k1zi3O9FF8GG2VyJQv8i4LGcwZE1Wrdd1iakWugXlHTnROD1wjmgIwN7f0UBX6VXztJ92NXqKus5CkfBioksi45uHLJJFbnz8vMXQCCkidW/VVg91GitMjN1s16JcXbBbQMShpmZ07Jub+zn7pIy2y6xHGQSRe3Z2wf7rI8VjqyH3OnuGT/HLLEaslGWuPTSaswoO1HljG61ttjoPk1czfeABeNQGzmzYgPEVENBRhjr46AR95Thyjbo803B/fsk/uFDVAVrLZZAveqQvl7gNcewLyRetDWKm95GM30Sl8vZkhHXJc9OIHu17QOnsjTKaBa2J6CVTT+E3f6Fc5Pyr4FxfZN/FK99MDf6GWFg=
